### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by jpmens** [lovenunu/leftpad-c#5] opened 2016-03-24 15:30 UTC
After #1 : 

```
$ cc -Wall -Werror leftpad-test.c leftpad.c
$ ./a.out
Test failed: left_pad("foo", 0) != ""
```

**Comment by jpmens** [comment] 2016-03-24 15:33
Sorry: should probably have written: after #3

**Comment by lovenunu** [comment] 2016-03-24 16:08
Well, the problem is fixed now \o/ I should have run the tests before merging. Thanks !

**Closed by lovenunu** 2016-03-24 16:08 UTC
Labels: bug
